common: &default_settings
  app_name: "Example"
  api_hostname: "http://api.example.com/"
  auth:
    enable: true
    username:
    password:

#
# Below this settings are principally used by developers
#
development:
  <<: *default_settings
  app_name: "ApiBootstraper (dev)"
  api_hostname: api.apibootstraper.dev
  auth:
    enable: false

test:
  <<: *default_settings
  auth:
    enable: false

staging:
  <<: *default_settings
  app_name: "Example (staging)"
  auth:
    enable: false

production:
  <<: *default_settings
